### ISSUE TITLE
h1 not allowed as element nested inside button

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/lovesea-fall-2017#1]
https://github.com/redacademy/lovesea-fall-2017/blob/19a9d93ddc71887b6058f089c302deb8925c6e14/themes/lovesea/front-page.php#L16

W3C validation issue: "Element h1 not allowed as child of element button in this context."

To fix, change the h1 to a span and style accordingly.

**Comment by rcass** [comment]
Looks resolved to me 👍
