### ISSUE TITLE
use CFS props for labels

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/lovesea-fall-2017#10]
https://github.com/redacademy/lovesea-fall-2017/blob/19a9d93ddc71887b6058f089c302deb8925c6e14/themes/lovesea/page-templates/wedding.php#L19

Same thing here in regards to using CFS labels instead e.g.

```
<?php
$props = CFS()->get_field_info( 'some_field' );
echo $props['label'];
```

**Comment by rcass** [comment]
Sweet! Looks resolved 👍
