### ISSUE TITLE
check if functions should run on every page

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/lovesea-fall-2017#14]
https://github.com/redacademy/lovesea-fall-2017/blob/19a9d93ddc71887b6058f089c302deb8925c6e14/themes/lovesea/js/scripts.js#L13

I think this function most likely is only needed on the front page.

Having events fire on all pages can cause performance issues, especially if the elements they are trying to alter don't exist on the page.

Wrap your function in a conditional to check if it's needed
e.g.

```
if($('.home').length){
  $(window).scroll(function() {
    if ($(document).scrollTop() > 3) {  
      $('.front-center-logo').addClass('shrink');
    } else {
      $('.front-center-logo').removeClass('shrink');
    }
  });
}
```

**Comment by rcass** [comment]
Looks like you implemented the solution above 👍
