### ISSUE TITLE
The element a must not appear as a descendant of the button element.

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/lovesea-fall-2017#2]
https://github.com/redacademy/lovesea-fall-2017/blob/19a9d93ddc71887b6058f089c302deb8925c6e14/themes/lovesea/front-page.php#L16

More W3C validation issues.

Basically since buttons usually act very similar to a <a> you shouldn't nest the 2
Just use either the <button> or the <a> element but not both.

**Comment by rcass** [comment]
Looks resolved 👍
