### ISSUE TITLE
CFS field labels

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/lovesea-fall-2017#8]
https://github.com/redacademy/lovesea-fall-2017/blob/19a9d93ddc71887b6058f089c302deb8925c6e14/themes/lovesea/archive-gallery.php#L23

Instead of hard-coding the tabs, since you're using CFS try echoing the label 

http://customfieldsuite.com/api/get_field_info.html

**Comment by rcass** [comment]
When I look at the archive-gallery.php, im still seeing the same issue as above

**Comment by rcass** [comment]
Looks like you just removed this code. I only see these changes in the develop branch, so dont forget to merge to master
