### ISSUE TITLE
function prefixes

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/lovesea-fall-2017#9]
https://github.com/redacademy/lovesea-fall-2017/blob/19a9d93ddc71887b6058f089c302deb8925c6e14/themes/lovesea/inc/extras.php#L14

It looks like you've done a good job in the functions file of prefixing with your theme name.
Try to refactor other functions as you come across them to be similar.

Not a huge issue but a good practice to follow and should help to avoid possible namespace conflicts

**Comment by rcass** [comment]
Overall good prefixing, however the function name for the enqueueing should be more descriptive that just lovesea. That name doesn't really describe the function at all.
